### PR TITLE
testing profiling plots

### PR DESCRIPTION
**Pull request by neelasha23**
Added image comparison on plots generated
Closes https://github.com/ploomber/sklearn-evaluation/issues/170

----
:books: Documentation preview :books:: https://ploomber-engine--32.org.readthedocs.build/en/32/

### CODE REVIEW

**Comment by neelasha23** [comment]
A couple of points : 
1. With `parametrize` the test was generating only one image whereas there should be two separate images for the two input values, so I created different methods with different baseline images.
2. Since `runtime` and `memory` values are changing with every run, the plots are also changing. Added `tol` value. Is this the right approach? If so, do we need to add some buffer to the `tol` value? As of now the tests seem to be passing in the CI

@idomic @edublancas

**Comment by edublancas** [comment]
> Since runtime and memory values are changing with every run, the plots are also changing. Added tol value. Is this the right approach? If so, do we need to add some buffer to the tol value? As of now the tests seem to be passing in the CI

to profile memory and runtime, we add metadata to the output notebook (`out` [variable here](https://github.com/ploomber/ploomber-engine/blob/bdc07d68f769cedd97765eb1e93daa87932160da/src/ploomber_engine/execute.py#L125)). What you can do is to mock the call to `client.execute` so it returns a pre-made notebook with particular memory usage and runtime values. this way, it'll have a deterministic behavior and you'll be able to test it.

some of the tests create notebook objects so check those out to know how to create a notebook. to mock, check out the docs and some tutorial on the unittest.mock module, remember you have to mock the class imported in the execute module. like this:

```python
from ploomber_engine import execute
from unittest.mock import Mock

def mock_client(monkeypatch):
    mock = Mock()
    monkeypatch.setattr(execute, "PloomberClient", mock)
```

mocking can be tricky sometimes so feel free to post questions if you have any challenges.

**Comment by edublancas** [comment]
on a second thought, I think it'll be simple to test [this function](https://github.com/ploomber/ploomber-engine/blob/bdc07d68f769cedd97765eb1e93daa87932160da/src/ploomber_engine/profiling.py#L65), this way we only need to create the sample notebook but there's no need to mock

**Comment by neelasha23** [comment]
Ok, will add tests for this function. but even with a sample pre-made notebook, I feel the runtime and memory usage might vary with every run. Are we looking for a solution where it is exactly same on every run?

**Comment by edublancas** [comment]
it won't vary. when executing a notebook, we record the runtime and memory in the notebook itself (eg., here we grab [memory measurements](https://github.com/ploomber/ploomber-engine/blob/bdc07d68f769cedd97765eb1e93daa87932160da/src/ploomber_engine/profiling.py#L75)). So what I'm suggesting is to fake those measurements so they always have the same values.

e.g., a cell in the notebook will look like this:

```json
{"metadata": {"ploomber": {"memory_usage": 100}}}
```

**Comment by neelasha23** [comment]
got it !

**Comment by edublancas** [comment]
any updates?

**Comment by neelasha23** [comment]
Have made the changes as discussed however I'm facing a weird issue with the plot_runtime testcase.

Getting this error:
```FAILED tests/test_profiling.py::test_plot_cell_runtime[png] - AssertionError: Test generated 0 images but there are 1 baseline images```

However when I run the test individually like ```ploomber-engine % pytest tests/test_profiling.py::test_plot_cell_runtime``` it is passing:

```
../../miniforge3/envs/sk-eval/lib/python3.10/site-packages/ansiwrap/core.py:6
  /Users/neelashasen/miniforge3/envs/sk-eval/lib/python3.10/site-packages/ansiwrap/core.py:6: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================== 1 passed, 1 warning in 0.76s ===========================================================
```

Still trying to figure out the issue

**Comment by neelasha23** [comment]
Update: The issue was with `gca`. Tests pass on my local after replacing it with `subplots`.
However I still see an issue with ubuntu, python 3.7. Number of images generated are inconsistent (sometimes 0, sometimes 2 or 3)

**Comment by edublancas** [comment]
> However I still see an issue with python 3.7. Number of images generated are inconsistent (sometimes 0, sometimes 2 or 3)

let's deprecate Python 3.7 form the CI, the official [end-of-life ](https://devguide.python.org/versions/#supported-versions) is scheduled for June 2023, but many projects in the data ecosystem (like numpy) already dropped support, that's probably why we're seeing this random errors, since 3.7 is no lo longer supported by many libraries

**Comment by edublancas** [comment]
please just add a note in the README saying we support Python >=3.8

**Comment by neelasha23** [comment]
Removed 3.7 from CI. Added in changelog as fix (although it's not a fix but I couldn't find a better tag)
@edublancas

**Review by edublancas — APPROVED** [review]

**Pull request merged**
