### PR TITLE
Add cwd to execute notebook

### LINKED ISSUE #53: add cwd to execute_notebook (kwarg exists in papermill)
`cwd` allows the user to set the path to execute a notebook. This feature is present as a kwarg in papermill: 
https://github.com/nteract/papermill/blob/54f6c038cdae0c70d5fb04691fa465e12aeb62cb/papermill/execute.py#L29

### PR DESCRIPTION
**Pull request by avivajpeyi**
## Describe your changes
Add `cwd` feature from `papermill` to `ploomber_engine`

## Issue ticket number and link
Closes #53 

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [x] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

----
:books: Documentation preview :books:: https://ploomber-engine--54.org.readthedocs.build/en/54/

### CODE REVIEW

**Comment by avivajpeyi** [comment]
@edublancas, any suggestions on the following tests that are failing? 

Screen Shot 2023-03-01 at 7 16 17 pm

**Comment by edublancas** [comment]
alright so almost all check passed, except the docs building. this is probably due to some external cause. I've fixed this in the main branch already, please rebase from main so you get the fix and push again

**Review by edublancas — CHANGES_REQUESTED** [review]
pretty good implementation!

just one minor thing: can you add a note to specify where this was added to the functions that got a new `cwd` argument? (except for `cli`):


```
    .. versionchanged:: 0.0.23
        Added ``cwd`` argument.
```

**Review by edublancas — APPROVED** [review]

**Comment by edublancas** [comment]
awesome! thanks for working on this, after the other PR is merged, I'll make a release!

**Pull request merged**
