### PR TITLE
Cleaned Notebook output and cell index

### LINKED ISSUE #59: clean notebook before execution
when copying the notebook for execution, we should clean it up and remove all the outputs and cell indexes

### PR DESCRIPTION
**Pull request by mehtamohit013**
## Describe your changes
Cleaned notebook output and cell index before executing

## Issue ticket number and link
Closes #59 

## Checklist before requesting a review

- [X] I have performed a self-review of my code
- [X] I have added thorough [tests](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#testing) (when necessary).
- [X] I have added the right documentation in the [docstring](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#documenting-changes-and-new-features) and [changelog](https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog) (when needed)

----
:books: Documentation preview :books:: https://ploomber-engine--62.org.readthedocs.build/en/62/

### CODE REVIEW

**Comment by edublancas** [comment]
is this ready for review? if so, please don't forget to request it from the right bar so we can get to it!

**Review by edublancas — CHANGES_REQUESTED** [review]
please add some unit tests

**Review by edublancas — CHANGES_REQUESTED** [review]
overall, it looks good! can you add a test that uses [`execute_notebook`](https://github.com/ploomber/ploomber-engine/blob/ecbcbff6dac74481f1e30062659b6c70fbb0b643/src/ploomber_engine/execute.py#L20)? use some notebook with cell indexes + outputs, and add a cell at the end that crashes on purpose.

then we should see that the original notebook remains unchanged but the output notebook has the outputs overwritten up until the failing cell, beyond that there are no cell indexes or outputs

**Comment by mehtamohit013** [comment]
I have wrote the test but the test is failing due to the fact that, whenever a cell crashes in ```execute_cell()```, the function will give me an error, because every result of cell is checked using ```result.raise_error()``` and the test will fail. I can add a parameter to ```execute()``` for this single test case like ```bypass_error``` which will run all the cells despite the earlier cell fail or succeed

**Comment by edublancas** [comment]
I think this should work:

```python
with pytest.raises(SomeError):
    execute_notebook()

# check that the notebook is cleaned up
```

this will capture the error and allow you to test the notebook.

**Comment by mehtamohit013** [comment]
As soon, ```execute()``` throws the error, pytest is terminating the test

```python
 with pytest.raises(NameError):
        out = client.execute()
        assert out == ......      
```
Here, `assert` statement is not checked

**Review by edublancas — CHANGES_REQUESTED** [review]
looks good! the only missing part is to edit the changelog: https://github.com/ploomber/contributing/blob/main/CONTRIBUTING.md#changelog

**Comment by mehtamohit013** [comment]
Hi @edublancas ,
I have added the changes in changelog and edited the version to 0.0.25, but the test is still failing. Can you please suggest me what went wrong ?

**Comment by edublancas** [comment]
we're following semver so we have a script that checks if there are any  API breaking changes and requires us to bump a major version release. In this case, the change you're making won't break the API so you can put it as `[Fix]` that will fix the problem

**Review by edublancas — APPROVED** [review]

**Pull request merged**
